# NumPy 


Numerical python - NumPy

It contains only Homogeneous Elements

In [1]:
l = [1, 2, 3, 'a', (1,3), {3:'d'}, [2,4], 2.4]

### Installing NumPy Library 

In [2]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


'c:\program' is not recognized as an internal or external command,
operable program or batch file.


In [3]:
import numpy

In [4]:
numpy.array([1,2,3,5])

array([1, 2, 3, 5])

In [5]:
a = numpy.array([2,4,6,7])

In [6]:
a

array([2, 4, 6, 7])

In [7]:
a.dtype

dtype('int32')

In [8]:
b = numpy.array([1,3,'a',6,7])

In [9]:
b.dtype

dtype('<U11')

In [13]:
b

array(['1', '3', 'a', '6', '7'], dtype='<U11')

In [10]:
c = numpy.array([1,2,3.4,6])

In [11]:
c.dtype

dtype('float64')

In [12]:
c

array([1. , 2. , 3.4, 6. ])

In [14]:
a

array([2, 4, 6, 7])

In [15]:
b

array(['1', '3', 'a', '6', '7'], dtype='<U11')

In [16]:
c

array([1. , 2. , 3.4, 6. ])

In [17]:
a = numpy.append(a,10) # appending single element into an array

In [18]:
a

array([ 2,  4,  6,  7, 10])

In [19]:
b = numpy.append(b,[11,22,33,44])

In [20]:
b

array(['1', '3', 'a', '6', '7', '11', '22', '33', '44'], dtype='<U11')

In [21]:
import numpy as np 

In [22]:
np.array([1,2,4])

array([1, 2, 4])

### arange 
 Creating an array with particular range of values

In [23]:
ar = np.arange(1,11)

In [24]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
ar.dtype

dtype('int32')

In [26]:
ar1 = np.arange(0,11,2) # range of elements with step values

In [27]:
ar1

array([ 0,  2,  4,  6,  8, 10])

In [28]:
ar3 = np.arange(1,100,10)

In [29]:
ar3

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [30]:
ar1.nbytes # checking the memory space

24

In [31]:
ar1

array([ 0,  2,  4,  6,  8, 10])

In [33]:
ar3.itemsize # each element size

4

In [34]:
ar1.itemsize

4

In [35]:
len(ar1) # length of an array

6

start value 1- end value 10 : 20 number of values

In [36]:
v = np.linspace(1,10, 20) # creating array with in the given range and give number of elemnets 

In [37]:
v

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [38]:
len(v)

20

In [39]:
l = np.logspace(1,10,20) # create a array whit in the range and required number of elemnets with their log values

In [40]:
l

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [43]:
v1 = np.full(5,'numpy') # repeating required number of time and making into an array 

In [42]:
v1

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy'], dtype='<U5')

In [44]:
v2 = np.full(100,8)

In [45]:
v2

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [47]:
b1= np.zeros(10)

In [48]:
b1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
b1.dtype

dtype('float64')

In [50]:
zeros = np.zeros(10,dtype=int)

In [51]:
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
zeros.dtype

dtype('int32')

In [55]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 2-d array 

In [58]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])      

In [59]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [60]:
a.dtype

dtype('int32')

In [61]:
a.itemsize

4

In [62]:
a.ndim

2

In [63]:
len(a)

3

### 3-d array

In [64]:
a2 = np.array([[[1,2,3,4],[4,5,6,7]],[[9,8,5,3],[2,3,4,6]]])

In [65]:
a2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 5, 3],
        [2, 3, 4, 6]]])

In [66]:
a2.ndim

3

### Multi Dimensional arrays

In [68]:
a3 = np.array([1,2,3,4,5,6,7],ndmin=20)

In [69]:
a3

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4, 5, 6, 7]]]]]]]]]]]]]]]]]]]])

In [70]:
a3.ndim

20

### Accessing the elements from the array

In [71]:
# 1-d array

a= np.array([1,2,3,4,5,6])

In [72]:
a

array([1, 2, 3, 4, 5, 6])

In [73]:
a[1]

2

In [74]:
a[-5]

2

In [75]:
a[-1]

6

In [76]:
a[1:4]

array([2, 3, 4])

In [77]:
a[-3:]

array([4, 5, 6])

In [78]:
a

array([1, 2, 3, 4, 5, 6])

In [80]:
## 2-d array 
b = np.array([[1,2,3,4],[5,6,7,8]])

In [81]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [82]:
b[0]

array([1, 2, 3, 4])

In [83]:
b[1]

array([5, 6, 7, 8])

In [84]:
b[0,2]

3

In [85]:
b[1,0]

5

In [86]:
b[:,-1]

array([4, 8])

In [87]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
b[:,-2]

array([3, 7])

In [89]:
b[:,-3:]

array([[2, 3, 4],
       [6, 7, 8]])

In [91]:
# 3-d array
a3d = np.array([[[1,2,3,4],[5,6,7,4]],[[9,8,7,6],[2,3,4,5]]])

In [92]:
a3d.ndim

3

In [93]:
a3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 4]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [96]:
a3d[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 4]])

In [95]:
a3d[1]

array([[9, 8, 7, 6],
       [2, 3, 4, 5]])

In [97]:
a3d[0,0]

array([1, 2, 3, 4])

In [98]:
a3d[0,0,2]

3

In [99]:
a3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 4]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [100]:
a3d[1,1,-2]

4

In [101]:
a3d[:,:,-1]

array([[4, 4],
       [6, 5]])

### Shape of an array

In [104]:
a = np.array((1,2,3))

In [105]:
a

array([1, 2, 3])

In [106]:
a.shape

(3,)

In [108]:
# 2d array
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
b.ndim

2

In [110]:
b.shape

(2, 4)

In [111]:
a3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 4]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [112]:
a3d.shape

(2, 2, 4)

### Size

In [113]:
a.size

3

In [114]:
a

array([1, 2, 3])

In [115]:
b.size

8

In [116]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
a3d.size

16

### Reshaping the array

In [119]:
a = np.arange(1,21)

In [120]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [121]:
a.size

20

In [124]:
b = a.reshape(4,5)

In [123]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [125]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [126]:
b.ndim

2

In [128]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [131]:
c = a.reshape(2,5,2)

In [132]:
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [134]:
c.ndim

3

In [135]:
a.reshape(5,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [136]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [137]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

### Iterate an array elements

In [138]:
l = [1,2,3,5]

In [139]:
for ele in l:
    print(ele)

1
2
3
5


In [140]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [141]:
a.ndim

1

In [143]:
for ele in a:
    print(ele, end= ':')

1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20:

In [144]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [145]:
b.ndim

2

In [147]:
for row in b:
    for ele in row:
        print(ele, end= " ::")

1 ::2 ::3 ::4 ::5 ::6 ::7 ::8 ::9 ::10 ::11 ::12 ::13 ::14 ::15 ::16 ::17 ::18 ::19 ::20 ::

In [148]:
a3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 4]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [151]:
for set_ in a3d:
    for row in set_:
        for ele in row:
            print(ele, end=" ")

1 2 3 4 5 6 7 4 9 8 7 6 2 3 4 5 

### nditer 

keyword forr iterating the array

np.nditer

In [154]:
for i in np.nditer(a3d):
    print(i ,end=" ")

1 2 3 4 5 6 7 4 9 8 7 6 2 3 4 5 

### joining the arrays

In [155]:
# 1-d array

a = np.arange(1,10)
b = np.arange(11,20)

In [156]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [159]:
c = np.concatenate((a,b))

In [160]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [161]:
# 2-d array 
a2 = a.reshape(3,3)
b2 = b.reshape(3,3)

In [162]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
b2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [165]:
c2 = np.concatenate((a2,b2))

In [166]:
c2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [167]:
# 3-d array

a3 = a.reshape(3,1,3)

In [168]:
a3

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [170]:
b3 = b.reshape(3,1,3)

In [171]:
b3

array([[[11, 12, 13]],

       [[14, 15, 16]],

       [[17, 18, 19]]])

In [172]:
c3 = np.concatenate((a3,b3))

In [173]:
c3

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[11, 12, 13]],

       [[14, 15, 16]],

       [[17, 18, 19]]])

#### To concatenate any two arrays the shape should be same and the dimensions also be same

### Stastical and Mathmetical operations on an array

In [175]:
b2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [176]:
np.min(b2)

11

In [177]:
np.max(b3)

19

In [178]:
b3.max()

19

In [180]:
c3.min()

1

In [181]:
c3.max()

19

In [182]:
np.max(c3)

19

In [183]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [184]:
c.argmin()

0

In [186]:
c3.argmin()

0

In [189]:
a3d.argmax()

8

In [191]:
a3d.mean()

4.75

In [192]:
c.mean()

10.0

In [193]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [194]:
c.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [195]:
np.median(c) # median of an array elements

10.0

In [196]:
np.average(a3d) # avearge of an array elements

4.75

In [197]:
np.average(b2)

15.0

In [198]:
# to calculate the standard deviation we can use std
np.std(a3d)

2.222048604328897

In [199]:
np.std(b2)

2.581988897471611

In [200]:
np.std(c)

5.627314338711377

In [201]:
np.sum(c)

180

In [202]:
np.sum(a3d)

76

In [204]:
b2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [205]:
np.sum(b2,1)

array([36, 45, 54])

In [206]:
np.sum(b2,0)

array([42, 45, 48])

1 --- row wise

0 --- column wise