# NumPy 


Numerical python - NumPy

It contains only Homogeneous Elements

In [1]:
l = [1, 2, 3, 'a', (1,3), {3:'d'}, [2,4], 2.4]

### Installing NumPy Library 

In [2]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


'c:\program' is not recognized as an internal or external command,
operable program or batch file.


In [3]:
import numpy

In [4]:
numpy.array([1,2,3,5])

array([1, 2, 3, 5])

In [5]:
a = numpy.array([2,4,6,7])

In [6]:
a

array([2, 4, 6, 7])

In [7]:
a.dtype

dtype('int32')

In [8]:
b = numpy.array([1,3,'a',6,7])

In [9]:
b.dtype

dtype('<U11')

In [13]:
b

array(['1', '3', 'a', '6', '7'], dtype='<U11')

In [10]:
c = numpy.array([1,2,3.4,6])

In [11]:
c.dtype

dtype('float64')

In [12]:
c

array([1. , 2. , 3.4, 6. ])

In [14]:
a

array([2, 4, 6, 7])

In [15]:
b

array(['1', '3', 'a', '6', '7'], dtype='<U11')

In [16]:
c

array([1. , 2. , 3.4, 6. ])

In [17]:
a = numpy.append(a,10) # appending single element into an array

In [18]:
a

array([ 2,  4,  6,  7, 10])

In [19]:
b = numpy.append(b,[11,22,33,44])

In [20]:
b

array(['1', '3', 'a', '6', '7', '11', '22', '33', '44'], dtype='<U11')

In [21]:
import numpy as np 

In [22]:
np.array([1,2,4])

array([1, 2, 4])

### arange 
 Creating an array with particular range of values

In [23]:
ar = np.arange(1,11)

In [24]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
ar.dtype

dtype('int32')

In [26]:
ar1 = np.arange(0,11,2) # range of elements with step values

In [27]:
ar1

array([ 0,  2,  4,  6,  8, 10])

In [28]:
ar3 = np.arange(1,100,10)

In [29]:
ar3

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [30]:
ar1.nbytes # checking the memory space

24

In [31]:
ar1

array([ 0,  2,  4,  6,  8, 10])

In [33]:
ar3.itemsize # each element size

4

In [34]:
ar1.itemsize

4

In [35]:
len(ar1) # length of an array

6

start value 1- end value 10 : 20 number of values

In [36]:
v = np.linspace(1,10, 20) # creating array with in the given range and give number of elemnets 

In [37]:
v

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [38]:
len(v)

20

In [39]:
l = np.logspace(1,10,20) # create a array whit in the range and required number of elemnets with their log values

In [40]:
l

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [43]:
v1 = np.full(5,'numpy') # repeating required number of time and making into an array 

In [42]:
v1

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy'], dtype='<U5')

In [44]:
v2 = np.full(100,8)

In [45]:
v2

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [47]:
b1= np.zeros(10)

In [48]:
b1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
b1.dtype

dtype('float64')

In [50]:
zeros = np.zeros(10,dtype=int)

In [51]:
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
zeros.dtype

dtype('int32')

In [55]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 2-d array 

In [58]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])      

In [59]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [60]:
a.dtype

dtype('int32')

In [61]:
a.itemsize

4

In [62]:
a.ndim

2

In [63]:
len(a)

3

### 3-d array

In [64]:
a2 = np.array([[[1,2,3,4],[4,5,6,7]],[[9,8,5,3],[2,3,4,6]]])

In [65]:
a2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 5, 3],
        [2, 3, 4, 6]]])

In [66]:
a2.ndim

3

### Multi Dimensional arrays

In [68]:
a3 = np.array([1,2,3,4,5,6,7],ndmin=20)

In [69]:
a3

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4, 5, 6, 7]]]]]]]]]]]]]]]]]]]])

In [70]:
a3.ndim

20

### Accessing the elements from the array

In [71]:
# 1-d array

a= np.array([1,2,3,4,5,6])

In [72]:
a

array([1, 2, 3, 4, 5, 6])

In [73]:
a[1]

2

In [74]:
a[-5]

2

In [75]:
a[-1]

6

In [76]:
a[1:4]

array([2, 3, 4])

In [77]:
a[-3:]

array([4, 5, 6])

In [78]:
a

array([1, 2, 3, 4, 5, 6])

In [80]:
## 2-d array 
b = np.array([[1,2,3,4],[5,6,7,8]])

In [81]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [82]:
b[0]

array([1, 2, 3, 4])

In [83]:
b[1]

array([5, 6, 7, 8])

In [84]:
b[0,2]

3

In [85]:
b[1,0]

5

In [86]:
b[:,-1]

array([4, 8])

In [87]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
b[:,-2]

array([3, 7])

In [89]:
b[:,-3:]

array([[2, 3, 4],
       [6, 7, 8]])

In [91]:
# 3-d array
a3d = np.array([[[1,2,3,4],[5,6,7,4]],[[9,8,7,6],[2,3,4,5]]])

In [92]:
a3d.ndim

3

In [93]:
a3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 4]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [96]:
a3d[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 4]])

In [95]:
a3d[1]

array([[9, 8, 7, 6],
       [2, 3, 4, 5]])

In [97]:
a3d[0,0]

array([1, 2, 3, 4])

In [98]:
a3d[0,0,2]

3

In [99]:
a3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 4]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [100]:
a3d[1,1,-2]

4

In [101]:
a3d[:,:,-1]

array([[4, 4],
       [6, 5]])

### Shape of an array

In [104]:
a = np.array((1,2,3))

In [105]:
a

array([1, 2, 3])

In [106]:
a.shape

(3,)

In [108]:
# 2d array
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
b.ndim

2

In [110]:
b.shape

(2, 4)

In [111]:
a3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 4]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [112]:
a3d.shape

(2, 2, 4)

### Size

In [113]:
a.size

3

In [114]:
a

array([1, 2, 3])

In [115]:
b.size

8

In [116]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
a3d.size

16

### Reshaping the array

In [119]:
a = np.arange(1,21)

In [120]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [121]:
a.size

20

In [124]:
b = a.reshape(4,5)

In [123]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [125]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [126]:
b.ndim

2

In [128]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [131]:
c = a.reshape(2,5,2)

In [132]:
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [134]:
c.ndim

3

In [135]:
a.reshape(5,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [136]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [137]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

### Iterate an array elements

In [138]:
l = [1,2,3,5]

In [139]:
for ele in l:
    print(ele)

1
2
3
5


In [140]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [141]:
a.ndim

1

In [143]:
for ele in a:
    print(ele, end= ':')

1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20:

In [144]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [145]:
b.ndim

2

In [147]:
for row in b:
    for ele in row:
        print(ele, end= " ::")

1 ::2 ::3 ::4 ::5 ::6 ::7 ::8 ::9 ::10 ::11 ::12 ::13 ::14 ::15 ::16 ::17 ::18 ::19 ::20 ::

In [148]:
a3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 4]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [151]:
for set_ in a3d:
    for row in set_:
        for ele in row:
            print(ele, end=" ")

1 2 3 4 5 6 7 4 9 8 7 6 2 3 4 5 

### nditer 

keyword forr iterating the array

np.nditer

In [154]:
for i in np.nditer(a3d):
    print(i ,end=" ")

1 2 3 4 5 6 7 4 9 8 7 6 2 3 4 5 

### joining the arrays

In [155]:
# 1-d array

a = np.arange(1,10)
b = np.arange(11,20)

In [156]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [159]:
c = np.concatenate((a,b))

In [160]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [161]:
# 2-d array 
a2 = a.reshape(3,3)
b2 = b.reshape(3,3)

In [162]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
b2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [165]:
c2 = np.concatenate((a2,b2))

In [166]:
c2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [167]:
# 3-d array

a3 = a.reshape(3,1,3)

In [168]:
a3

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [170]:
b3 = b.reshape(3,1,3)

In [171]:
b3

array([[[11, 12, 13]],

       [[14, 15, 16]],

       [[17, 18, 19]]])

In [172]:
c3 = np.concatenate((a3,b3))

In [173]:
c3

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[11, 12, 13]],

       [[14, 15, 16]],

       [[17, 18, 19]]])

#### To concatenate any two arrays the shape should be same and the dimensions also be same

### Stastical and Mathmetical operations on an array

In [175]:
b2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [176]:
np.min(b2)

11

In [177]:
np.max(b3)

19

In [178]:
b3.max()

19

In [180]:
c3.min()

1

In [181]:
c3.max()

19

In [182]:
np.max(c3)

19

In [183]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [184]:
c.argmin()

0

In [186]:
c3.argmin()

0

In [189]:
a3d.argmax()

8

In [191]:
a3d.mean()

4.75

In [192]:
c.mean()

10.0

In [193]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [194]:
c.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [195]:
np.median(c) # median of an array elements

10.0

In [196]:
np.average(a3d) # avearge of an array elements

4.75

In [197]:
np.average(b2)

15.0

In [198]:
# to calculate the standard deviation we can use std
np.std(a3d)

2.222048604328897

In [199]:
np.std(b2)

2.581988897471611

In [200]:
np.std(c)

5.627314338711377

In [201]:
np.sum(c)

180

In [202]:
np.sum(a3d)

76

In [204]:
b2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [205]:
np.sum(b2,1)

array([36, 45, 54])

In [206]:
np.sum(b2,0)

array([42, 45, 48])

1 --- row wise

0 --- column wise

## Day 4 Numpy continues

**Stacking :**
    arranging / organising an array into the appropriate way
    
    - Vertical stacking (vstack)
    - Horizontal stacking (hstack)

In [2]:
import numpy as np

In [3]:
a = np.arange(1,10)

In [5]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a = a.reshape(3,3)

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.hstack(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.vstack(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
b = np.arange(1,13).reshape(3,4)

In [12]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
np.hstack((a,b))

array([[ 1,  2,  3,  1,  2,  3,  4],
       [ 4,  5,  6,  5,  6,  7,  8],
       [ 7,  8,  9,  9, 10, 11, 12]])

In [14]:
np.vstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [15]:
b.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [16]:
np.vstack((a,b.T))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [17]:
np.sqrt(a) # Square root of an array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [18]:
 np.exp(a) # exponential of the array elements 

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [19]:
np.sin(a) # sine of the array elements 

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [20]:
np.cos(b) # cosine of the array elements 

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003],
       [-0.91113026, -0.83907153,  0.0044257 ,  0.84385396]])

In [21]:
np.tan(b) # tan of the array elements 

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00],
       [-3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
        -6.79971146e+00],
       [-4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
        -6.35859929e-01]])

In [22]:
np.log(b) # log of the array elements base "e"

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [23]:
np.log2(b) # log of the array elements base "2"

array([[0.        , 1.        , 1.5849625 , 2.        ],
       [2.32192809, 2.5849625 , 2.80735492, 3.        ],
       [3.169925  , 3.32192809, 3.45943162, 3.5849625 ]])

In [24]:
np.log10(b) # log of the array elements base "10"

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125]])

In [25]:
np.remainder(b,3) # remainder of the array elements

array([[1, 2, 0, 1],
       [2, 0, 1, 2],
       [0, 1, 2, 0]], dtype=int32)

In [26]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
np.degrees(b)

array([[ 57.29577951, 114.59155903, 171.88733854, 229.18311805],
       [286.47889757, 343.77467708, 401.07045659, 458.3662361 ],
       [515.66201562, 572.95779513, 630.25357464, 687.54935416]])

In [28]:
np.ediff1d(b) # converts the array into 1-d and calculate the consecutive differences of each element

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
np.i0(b) # bessel function 

array([[    1,     2,     4,    11],
       [   27,    67,   168,   427],
       [ 1093,  2815,  7288, 18948]])

In [31]:
np.mod(b,2) # Modulous of array elements

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]], dtype=int32)

In [33]:
np.power(b, 4) #power of array elements

array([[    1,    16,    81,   256],
       [  625,  1296,  2401,  4096],
       [ 6561, 10000, 14641, 20736]], dtype=int32)

In [35]:
np.power(b,2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]], dtype=int32)

In [36]:
help(np.power)

Help on ufunc object:

power = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array

In [37]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
b* 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [39]:
np.multiply(b,2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [40]:
b/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

In [41]:
np.divide(b,2)

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

In [42]:
c = np.array([1+2j, 2+3j, 3+4j])

In [43]:
c

array([1.+2.j, 2.+3.j, 3.+4.j])

In [45]:
np.real(c)

array([1., 2., 3.])

In [46]:
np.imag(c)

array([2., 3., 4.])

In [47]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
c

array([1.+2.j, 2.+3.j, 3.+4.j])

In [50]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a1 = a

In [52]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
a[0] = 111

In [55]:
a

array([[111, 111, 111],
       [  4,   5,   6],
       [  7,   8,   9]])

In [56]:
a1

array([[111, 111, 111],
       [  4,   5,   6],
       [  7,   8,   9]])

**Ravel and Flatten :**
    
    - Ravel : used to copy of the original array. when any changes made in  the duplicate array those chages are applied to the original array also
    - Flatten : used to copy of the original array. when any changes made in  the duplicate array those chages are not applied to the original array also
    

In [58]:
original = np.arange(1,10)

In [60]:
original

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
copy = original.ravel()

In [62]:
copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
copy[0] = 100

In [64]:
copy

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [65]:
original

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [66]:
copy2 = original.flatten()

In [67]:
copy2

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [68]:
original

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [69]:
copy2[0] = 0

In [70]:
copy2

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
original 

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

### Random methods:

In [72]:
np.random.randint() 

TypeError: randint() takes at least 1 positional argument (0 given)

In [74]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [75]:
np.random.randint(100) # it returns a random integer value with in the range

7

In [76]:
np.random.randint(100)

74

In [77]:
np.random.randint(100)

92

In [78]:
np.random.randint(1,100)

93

In [79]:
np.random.randint(50,100)

67

In [81]:
np.random.rand() # float value from 0 - 1 range

0.8516951253312907

In [82]:
np.random.randint(50,100, size = (20))

array([58, 91, 96, 52, 65, 63, 63, 90, 92, 83, 53, 87, 88, 72, 56, 59, 78,
       80, 72, 77])

In [83]:
np.random.randint(50,100, size = (3,3))

array([[67, 78, 67],
       [58, 85, 78],
       [80, 62, 93]])

In [84]:
np.random.randint(50,100, size = (3,2,5))

array([[[68, 69, 87, 93, 91],
        [96, 73, 96, 72, 78]],

       [[67, 94, 90, 87, 86],
        [80, 77, 97, 73, 98]],

       [[61, 80, 94, 79, 55],
        [69, 82, 91, 50, 74]]])

In [85]:
np.random.choice([2,4,5,7,8,90,12,45])

8

In [86]:
np.random.choice([2,4,5,7,8,90,12,45])

2

In [87]:
np.random.choice([2,4,5,7,8,90,12,45], size=(2,2))

array([[ 5,  2],
       [ 8, 45]])

In [89]:
np.random.choice([2,4,5,7,8,90,12,45,11], size= (2,2,3))

array([[[12, 12, 90],
        [ 5, 12, 90]],

       [[45,  4,  4],
        [90, 45, 11]]])

In [90]:
a

array([[111, 111, 111],
       [  4,   5,   6],
       [  7,   8,   9]])

In [91]:
np.random.shuffle(a)

In [92]:
a

array([[  4,   5,   6],
       [111, 111, 111],
       [  7,   8,   9]])

In [93]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
np.random.shuffle(b)

In [96]:
b

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [104]:
np.random.binomial(10,p=[0.1], size=(5))

array([0, 1, 0, 4, 3])

### Array Filtering 

In [105]:
a = np.array(np.random.randint(1,30,size=(9)))

In [106]:
a

array([17, 16,  9, 11,  1, 15, 18, 11, 28])

In [107]:
b = [False , True, False, False, True, True, False, True,False ]

In [108]:
c = a[b]

In [109]:
c

array([16,  1, 15, 11])

In [110]:
a

array([17, 16,  9, 11,  1, 15, 18, 11, 28])

In [111]:
b = []
for ele in a:
    if ele > 15:
        b.append(True)
    else:
        b.append(False)

In [112]:
a[b]

array([17, 16, 18, 28])

In [113]:
a

array([17, 16,  9, 11,  1, 15, 18, 11, 28])

In [115]:
b = a>15

In [116]:
a[b]

array([17, 16, 18, 28])

In [117]:
array = np.random.randint(100,size=(50,50))

In [118]:
array

array([[90, 20, 52, ..., 29,  0, 98],
       [52, 53, 91, ..., 41, 61,  7],
       [17, 57, 49, ..., 76, 30, 70],
       ...,
       [51, 99, 37, ..., 51, 26, 51],
       [55, 21, 87, ..., 39, 74, 50],
       [75, 61,  8, ..., 20, 45, 66]])

In [119]:
np.save('sample_array1',array)

In [120]:
np.load('sample_array1.npy')

array([[90, 20, 52, ..., 29,  0, 98],
       [52, 53, 91, ..., 41, 61,  7],
       [17, 57, 49, ..., 76, 30, 70],
       ...,
       [51, 99, 37, ..., 51, 26, 51],
       [55, 21, 87, ..., 39, 74, 50],
       [75, 61,  8, ..., 20, 45, 66]])

In [122]:
a

array([17, 16,  9, 11,  1, 15, 18, 11, 28])

In [123]:
np.save('test_array',a)

In [124]:
np.load('test_array.npy')

array([17, 16,  9, 11,  1, 15, 18, 11, 28])

In [126]:
a

array([17, 16,  9, 11,  1, 15, 18, 11, 28])

In [127]:
c

array([16,  1, 15, 11])

In [128]:
np.savez('test_zip', x=a ,y=c)

In [130]:
h = np.load('test_zip.npz')

In [132]:
h['x']

array([17, 16,  9, 11,  1, 15, 18, 11, 28])

In [133]:
h['y']

array([16,  1, 15, 11])

In [134]:
a1 = np.random.randint(1,10,size=(3,3))

In [135]:
a1

array([[2, 3, 1],
       [1, 5, 7],
       [2, 3, 5]])

In [136]:
m = np.dot(a1,a1.T)

In [137]:
m

array([[14, 24, 18],
       [24, 75, 52],
       [18, 52, 38]])

In [138]:
np.linalg.inv(m)

array([[ 0.18622449,  0.03061224, -0.13010204],
       [ 0.03061224,  0.26530612, -0.37755102],
       [-0.13010204, -0.37755102,  0.60459184]])

Stacking Helpers : R and C

In [139]:
np.c_[1:16]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [140]:
np.r_[1:16]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [141]:
a2 = np.r_[1:16]

In [142]:
a2.repeat(2)

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,
        9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15])

In [144]:
a2.repeat(4)

array([ 1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  5,
        5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,
        9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13,
       13, 14, 14, 14, 14, 15, 15, 15, 15])

In [145]:
a1

array([[2, 3, 1],
       [1, 5, 7],
       [2, 3, 5]])

In [146]:
a1.repeat(2,axis=1)

array([[2, 2, 3, 3, 1, 1],
       [1, 1, 5, 5, 7, 7],
       [2, 2, 3, 3, 5, 5]])

In [147]:
a1.repeat(2,axis=0)

array([[2, 3, 1],
       [2, 3, 1],
       [1, 5, 7],
       [1, 5, 7],
       [2, 3, 5],
       [2, 3, 5]])